spring:
  application:
    name: venda-consignada-api
  data:
    mongodb:
      uri: ${MONGODB_URI:mongodb://localhost:27017/venda-consignada?serverSelectionTimeoutMS=2000}

server:
  port: ${PORT:8080}

app:
  upload-dir: ${UPLOAD_DIR:uploads}
